package com.ojijo.o_invest.navigation

const val ROUT_HOME = "home"
const val ROUT_ABOUT = "about"
const val ROUT_START = "start"
const val ROUT_DASHBOARD = "dashboard"
const val ROUT_SERVICE = "service"
const val ROUT_SPLASH = "splash"
const val ROUT_FORM = "form"
const val ROUT_INVEST = "invest"
const val ROUT_SENDMONEY = "sendmoney"
const val ROUT_WITHDRAW = "withdraw"
const val ROUT_CONTACT = "contact"
const val ROUT_PROFILE = "profile"
const val ROUT_BILLSAIRTIME = "billsairtime"
const val ROUT_REVERSAL = "reversal"
const val ROUT_MPESAPAYBILL = "mpesapaybill"
const val ROUT_CAMERACAPTURE = "camera"
const val ROUT_PORTFOLIO = "portfolio"
const val ROUT_SETTING = "setting"
const val ROUT_TOPUP = "topup"

const val ROUT_REGISTER = "Register"
const val ROUT_LOGIN = "Login"

